set-option -a terminal-features "xterm-256color:RGB"
set -g prefix C-SPACE
set -g base-index 1
set -g renumber-windows on
set -g status-position top
set -g status-justify absolute-centre
set -g status-style "bg=default"
set -g status-left "#S "
set -g status-right ""
set -g window-status-current-style "fg=black bg=white"
set -g mode-keys vi
set -g allow-passthrough on

bind r source-file "~/.config/tmux/tmux.conf"
bind g run-shell "~/.config/scripts/open-git.sh"
bind f run-shell "tmux neww ~/.config/scripts/tmux-session-picker.sh"
bind N run-shell "tmux neww ~/.config/scripts/tmux-session-picker.sh ~/Documents/notes"
bind C run-shell "~/.config/scripts/tmux-session-picker.sh ~/.config"
bind n run-shell '~/.config/scripts/tmux-session-creator.sh'
bind SPACE last-window
